### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by thomas159** [mrmlnc/vscode-pugbeautify#3]
When I run beautify pug/jade on a selected block of html code it doesn't convert

**Comment by mrmlnc** [comment]
Hello, @thomas159,

Now, this plugin does not support formatting of selected block of code. Because if you select any part of code and run this plugin, it will work not correctly. For example:

**before**

``` jade
\t\t\t.class
\t\t\t\t\t.class
```

**after**

``` jade
\t.class
\t\t.class
```

**expected**

``` jade
\t\t\t.class
\t\t\t\t.class
```

**Comment by thomas159** [comment]
I'm not sure how to use this plugin then as opening an html file and running Beautify pug/jade doesn't work for me, selected or no selected html

**Comment by mrmlnc** [comment]
👀 Why you talking about HTML when this plugin works with a Jade/Pug? You can provide code or GIF?

**Comment by thomas159** [comment]
Sorry, think I got the wrong idea of what this did, thought it converted
html to pug, seems nto, delete my issue and I've given you a good review ;)

**Comment by mrmlnc** [comment]
For convert HTML to Jade/Pug you can use https://marketplace.visualstudio.com/items?itemName=wmaurer.html2jade or http://html2jade.org/
